// Bundles the AeroAgro Figma plugin: plugin logic + live data snapshot + PNG renders → code.js
// Usage: node scripts/build_figma_plugin.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'design', 'figma-plugin');
const data = JSON.parse(readFileSync(join(root, 'data.json'), 'utf8'));
const images = Object.fromEntries(
  readdirSync(join(root, 'assets'))
    .filter((f) => f.endsWith('.png'))
    .map((f) => [f.replace(/\.png$/, ''), readFileSync(join(root, 'assets', f)).toString('base64')])
);
const logic = readFileSync(join(root, 'src', 'plugin.js'), 'utf8');

const out = [
  '// GENERATED by scripts/build_figma_plugin.mjs, edit src/plugin.js instead.',
  `const DATA = ${JSON.stringify(data)};`,
  `const IMAGES = ${JSON.stringify(images)};`,
  logic,
].join('\n');
writeFileSync(join(root, 'code.js'), out);
console.log(`code.js: ${(out.length / 1024).toFixed(0)} KB · images: ${Object.keys(images).join(', ')} · region: ${data.region.name}`);
